# # This section gives the basic usages of numpy library functions


In [1]:
# Import the numpy module
import numpy as np

In [46]:
#Create array using numpy arange function
array=np.arange(2,10,2)
print(array)

[2 4 6 8]


In [2]:
#the below code produces the single dimension array through list
list=[1,2,3]
data=np.array(list)

print(data)

[1 2 3]


In [3]:
#the below code produces the two dimension dimension array trhough list of list

list=[[1,2,3],[3,4,5]]
data=np.array(list)
print(data)

[[1 2 3]
 [3 4 5]]


In [4]:
#The below method gives zeros matrix based on passed shaped values

zero_metrix=np.zeros((2,2))


In [5]:
print(zero_metrix*5)

[[0. 0.]
 [0. 0.]]


In [6]:
#The below method gives ones matrix based on passed shaped values

ones_metrix=np.ones((2,2))

print(ones_metrix*5)

[[5. 5.]
 [5. 5.]]


In [45]:
# create empty array using numpy

empty_array=np.empty([3,2], dtype = int) 
print(empty_array)




[[0 0]
 [0 0]
 [0 0]]


In [44]:
#The below code produces the complex array ....
#where dType is optional which means =desired DataTypes

data=[1,2,3]
complex_array=np.array(data,dtype = complex)
print(complex_array)

[1.+0.j 2.+0.j 3.+0.j]


In [13]:
# The below code gives the shape of the array or size of the array
a = np.array([[1,2,3],[4,5,6]]) 
#Print the array value
print(a)
#Print the size or shape of the array
print (a.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [28]:
#Reshape the array 
a=np.array([[1,23,45],[44,6575,45]])

#Print the actual array values 

print("Actual array values---->>>>>",a)

print("====================")

#Print the reshaped array data
b=a.reshape(3,2)
print("Print the reshaped array values----->>>>>>",b)


Actual array values---->>>>> [[   1   23   45]
 [  44 6575   45]]
Print the reshaped array values----->>>>>> [[   1   23]
 [  45   44]
 [6575   45]]
